### ISSUE TITLE
errors when run

### ISSUE THREAD

**Issue by Vexet83** [K0p1-Git/cloudflare-ddns-updater#10]
I get the following errors when I run the script. I have tried it on Ubuntu 20.04.3(VM), Ubuntu 21.04(VM), and Raspbian OS Lite(Raspberry Pi 4).

./cloudflare.sh: 17: [: <my IP>: unexpected operator
./cloudflare.sh: 25: [: global: unexpected operator
./cloudflare.sh: 41: [[: not found
./cloudflare.sh: 51: [[: not found

**Comment by K0p1-Git** [comment]
does the error still persist?

**Comment by Vexet83** [comment]
I didn't go into the other issues prior to posting this. after doing the command in the API issue it worked.
