### ISSUE TITLE
the IP in Cloud Flare doesn't get updates  

### ISSUE THREAD

**Issue by abdul-billy** [K0p1-Git/cloudflare-ddns-updater#12]
Hi 

I'm running the latest version as im writing this, I have tried everything but still the IP in CloudFlare doesn't update. So is there anything I have to do in Cloud Flare. I didn't get any output from the script.

**Comment by danpeig** [comment]
To read the script outputs, run "journalctl -xe" from your console.

**Comment by K0p1-Git** [comment]
Hi @abdul-billy, there is a known issue about the script going into an update loop if certain TLD was used. Clouldflare's API does not support domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard.

**Comment by K0p1-Git** [comment]
> To read the script outputs, run "journalctl -xe" from your console (recent linux distros).

Additionally, all logs from the script are written and stored under `/dev/log`

**Comment by abdul-billy** [comment]
first of all thanks guys for the quick replay, I have check the script output and apparently it works just fine. The issue is that im using .tk TLD, so im gonna try out something else. the problem is that some guys such as NetworkChuck was using .tk TLD and it worked great for him so that what throwed me off. 

Thanks 
Abdullah
