### ISSUE TITLE
adding systemd timers + service files & instructions to README.md or directory

### ISSUE THREAD

**Issue by SirBillyMays** [K0p1-Git/cloudflare-ddns-updater#15]
Hi,
As I prefer to keep everything managed through config files and sentralized to systemd services, I have created some basic configuration files and a timer for using this script w. systemd. I was wondering if a PR with these files (and some instructions) would be likely to be accepted, or would be rejected on the basis of the primary maintainer not wanting to "support" systemd.

If you're positive, I'll polish the files/instructions a little and make a PR. If you're not, I'll just publish them to my own public repo.

//fm

**Comment by K0p1-Git** [comment]
Hi,

Sorry for the late reply, I have been occupied with work for the past couple of days. Feel free to fork out of this repo with your variation. I am thinking of keeping this simple and intuitive for everyone to use.

Thanks!

**Comment by Adito5393** [comment]
Hey @SirBillyMays 
Can you share your systemd config?

**Comment by SirBillyMays** [comment]
@Adito5393 Sure can! It's currently a bit messy (never got around to cleaning it up), but here's my current "workflow". Just ask me if you have any questions :)

The TL;DR: is that the run-all-zones.sh script is called by the systemd service/timer. The run-all-zones.sh script then calls all the scripts in the individual_zones folder (all of which are just individually configured versions of the script from this repo.) I have to use that because I personally have a few different domains that I move around from server to server on occasion, and this affords me some easy flexibility. If you only have one domain, then you can replace the "ExecStart" line below to point directly to the DDNS script from this repo.

1.     Pull down the original repo: https://github.com/K0p1-Git/cloudflare-ddns-updater
2.     make a dedicated service user w. useradd -r (I called mine "ddns-cloudflare")
3.     Make a dedicated folder. /bin or /etc would arguably work
4.     Make the subfolder individual_zones, then add each individual zone script to that folder.
4.1 chmod -R 700 dedicated_service_folder && chown -R service_user:service_user dedicated_service_folder
5.     Copy the ddns-cloudflare.service and .timer to /lib/systemd/system/, and modify the path(s) and timings to your leisure
6.     Enable the service by reloading systemctl daemon-reload, then typing "systemctl start ddns-cloudflare.timer", "systemctl enable ddns-cloudflare.timer"
7.     Logging from the service is available in journalctl -xe. You can also check the status by using "systemctl status ddns-cloudflare.timer"

Keep in mind that 1200 request per 5 minutes is the maximum allowed by the cloudflare API

If you are only changing one zone, then you can launch the cloudflare-ddns-updater script directly from the ddns-cloudflare.service

### run-all-zones.sh
```

#!/bin/bash
set -e
cd /etc/ddns-cloudflare/individual_zones
for f in *.sh; do
  bash "$f"
done

```

### ddns-cloudflare.service

```
[Unit]
Description=cloudflare DDNS script

[Service]
Type=oneshot
ExecStart=/bin/bash /etc/ddns-cloudflare/run_all_zones.sh
User=ddns-cloudflare
Group=ddns-cloudflare

[Install]
WantedBy=multi-user.target
```

### ddns-cloudflare.timer

```
[Unit]
Description=Cloudflare DDNS timer
After=network-online.target

[Timer]
OnUnitActiveSec=30s

[Install]
WantedBy=timers.target
```

**Comment by Adito5393** [comment]
Thanks @SirBillyMays for the fast reply.
This gives me a nice example to build on top of it. I will add a few more parameters to the service file. (Inspired by [the caddy service](https://github.com/caddyserver/dist/blob/master/init/caddy.service))

### ddns-cloudflare.service
```bash
[Unit]
Description=cloudflare DDNS script
After=network.target network-online.target
Wants=network-online.target
AssertFileIsExecutable=/etc/ddns-cloudflare/run_all_zones.sh

... 
```
I will add the final version on my [personal branch](https://github.com/Adito5393/cloudflare-ddns-updater/tree/personal) when it's ready.
