### ISSUE TITLE
Suggest: allowing for multiple record_names

### ISSUE THREAD

**Issue by d-tork** [K0p1-Git/cloudflare-ddns-updater#22]
I came here from NetworkChuck, and at the end he tells viewers they can just set up CNAME records so they don't have to run this script for each subdomain. But that's not the whole story, as I believe it's normal practice to have _two_ A records: **mydomain.com**, and **www**. 

What I've taken to doing is passing `record_name` as a command line argument and just running two cronjobs, like so:

```bash
# cloudflare-init.sh
# ...
zone_identifier="abc123efg456" 
record_name=$1
ttl="3600"
# ...
```
```bash
# crontab
*/5 * * * * /bin/bash /home/user/cloudflare-ddns-updater/cloudflare-init.sh mydomain.com
*/5 * * * * /bin/bash /home/user/cloudflare-ddns-updater/cloudflare-init.sh www.mydomain.com
```

I suppose I could submit a PR with a for-loop wrapping the entire contents of the script, going through arguments until there are none left... but I am not a bash aficionado and perhaps someone has a better way or a better overall solution?

**Comment by K0p1-Git** [comment]
I'll leave this open for discussion. Thanks for the suggestion!

**Comment by timetoexpire** [comment]
I think that I have been able to get it working, hopefuly it works for you. Also got it to be able output lot debug info with -debug
*/5 * * * * /bin/bash ...../cloudflare-init.sh mydomain.com www.mydomain.com 

PS Never used github before hopefully I did this correct way.
https://github.com/timetoexpire/cloudflare-ddns-updater

**Comment by timetoexpire** [comment]
There few issue which I need to change. Few issue that need fixing. It will make it lot more flexible and easyer to add in new features in the code base. 

Sorry about my mistakes but I reather new using Git / Github.

**Comment by blackwatercitadel** [comment]
> I'll leave this open for discussion. Thanks for the suggestion!

It would be much appreciated if you could add the support for multiple domains. I have been using your script for some time on a single domain and just recently purchased 2 more. If you could also add to get an email notification once the DNS record is updated.

Would I have to run this script on a sub-domain as well? Wouldn't a CNAME work, I could be wrong?

**Comment by timetoexpire** [comment]
CNAME is pointer to A (IPv4) or AAAA (IPv6) records.  There nothing stoping you using test.example.org to point to card.example.com. So test.example.com has an IP of 192.158.1.38 and card.example.org also has IP of 192.158.1.38.  The big disadvange of doing this is mutiable DNS lookup that needed from example.org and then on example.com.

DNS Recorded for _example.com_
A - test - 192.158.1.38

DNS Recorded for _example.org_
CNAME - card - test.example.com

The is one thing you have look out for using cloudflare and A/AAAA being proxed could create an unresolvable issue.

**Comment by timetoexpire** [comment]
> It would be much appreciated if you could add the support for multiple domains. I have been using your script for some time on a single domain and just recently purchased 2 more. If you could also add to get an email notification once the DNS record is updated.

Well I have just add e-mail repoting status support to my version alongside with Slack. https://github.com/timetoexpire/cloudflare-ddns-updater (i have only tested using gmail, but dont let you testing other email SMTP servers)
