### ISSUE TITLE
Support for IPv6?

### ISSUE THREAD

**Issue by icebarf** [K0p1-Git/cloudflare-ddns-updater#27]
Does this script have support for ipv6 addresses as well?

**Comment by timetoexpire** [comment]
Should be rather easy to do as it just AAAA(IPv6) address. My ISP at the moment hasn't granted me access to IPv6 service. So I can not do any checks using IPv6 at https://ipv6.icanhazip.com/.

**Comment by dvcrn** [comment]
It's also worth noting that with a proper IPv6 implementation the ISP would assign your end device a permanent IPv6 address (alongside some temporary ones), so you could always use the permanent one and wouldn't need a DDNS script

**Comment by lnyousif** [comment]
I do not want to create a new issue, and I see that there is an IPv6 update, but any reason why it's not part of this code base? It seems like it belongs here. preferably auto-detecting the IP version. Its brilliant code though, thank you

**Comment by K0p1-Git** [comment]
@lnyousif Hi, as of now the use case of having to use DDNS for IPV6 is quite rare. With the lack of ability to test, and integrate it was decided to be left out.
