### ISSUE TITLE
Duplicate DNS Record

### ISSUE THREAD

**Issue by RiccardoBarbieri** [K0p1-Git/cloudflare-ddns-updater#28]
Every time a update occurs the record I set to be updated is actually being duplicated with the new IP address and the old one remains and I have to remove it by hand. How can I fix it?

**Comment by Sailboat265** [comment]
Hiii, are you using the latest version of the script? The issue has been fixed awhile ago.

**Comment by RiccardoBarbieri** [comment]
I downloaded the last version, will wait for next IP change and see if the problem is solved. Do you know which commit solved this bug? I would like to take a lool to the differences.

**Comment by Sailboat265** [comment]
Sure thing, PR #20 should have solved the bug if not already.

**Comment by K0p1-Git** [comment]
As mentioned by @Sailboat265 , the latest version of the script will fix this issue.

**Comment by RiccardoBarbieri** [comment]
Updated to the last version and the issue is resolved, thanks!
