### ISSUE TITLE
Multiple ddns updates

### ISSUE THREAD

**Issue by myhobby2** [K0p1-Git/cloudflare-ddns-updater#33]
Finally a script that works flawless! Thanks for that!

Only thing that is missing is a multi domain config file that can be used. I have 8 domains but I don't want 8 scripts ;-)
Is that something that can be considered ? If so, I can offer myself as beta tester ;-)

Keep up the good work !

**Comment by timetoexpire** [comment]
https://github.com/timetoexpire/cloudflare-ddns-updater

**Comment by myhobby2** [comment]
Thanks for your help but I can need some more because the documentation is rather cryptic. I have installed your forked script and it works for 1 domain. But I'm stuck how to update 

domain1.org
domain2.co.uk
.....

These have all different parameters but no clue how to proceed with a config-file. Is this possible or do I need to create a script for each domain ? Your mail function is very useful but... can you configure it (when to sent an email) and how can I test it. I think the info is in the source code, but that is not my cup of tea (I hardly can read it)

**Comment by timetoexpire** [comment]
With config file it would go somthing like. This
```
-zone_identifier="xyz45678901234567890123456789001"
-record_name="domain1.org"
-zone_identifier="abc45678901234567890123456789002"
d542e0aeab6d68ad70e43e871ca0c953
-record_name="domain2.co.uk"
```

As diffent domains use diffrent zone identifier.
The thing got to make shore that _API Zone Resources_ (auth/_key) for that is allow to edit the record for both domain1.org and domain2.co.uk. If the have diffrent then have do something like

```
-zone_identifier="xyz45678901234567890123456789001"
-auth_key="123456789012345679456446"
-record_name="domain1.org"
-zone_identifier="abc45678901234567890123456789002"
-auth_key="546833542486404054803540"
-record_name="domain2.co.uk"
```
You can use white space.
```
-zone_identifier="xyz45678901234567890123456789001"
  -auth_key="123456789012345679456446"
  -record_name="domain1.org"

-zone_identifier="abc45678901234567890123456789002"
  -auth_key="546833542486404054803540"
  -record_name="domain2.co.uk"
```
I would recomed that edit the config_file using Linux. If edit in using Windows need to remove \CR, this has fix in next version coming latter on this mounth.

**Comment by myhobby2** [comment]
Do you have a working example of a config file ? Or is it the above in a file (eg. cf_ddns.ini) and configured in your script header like depicted below?

proxy=false                                                       # Set the proxy to true or false
slackuri=""                                                        # URI for Slack WebHook "https://hooks.slack.com/services/xxxxx"
config_file="/install/dns-updater/cf_ddns.ini"     # set path and configuration-file name

email_username=

**Comment by timetoexpire** [comment]
That what that look like in config_file
```
-proxy="true"

-proxy="false"

-slackuri="https://hooks.slack.com/services/12345678"
```

You can not call config_file with in config_file. You can only have 1 config_file running. You set within the script (.sh) or bash line
```
# cloudflare_template.sh -config_file="/install/dns-updater/cf_ddns.ini"
```

```
-email_username="test@gmail.com"
-email_password="abcdfsd"
-email_smtp="smtp.gmail.com"
-email_fromAddress="test+clf20220126@gmail.com"
-email_fromName="Cloudflare 20220126"
-email_toAddress="testme@gmail.com"
-email_toName="Hello There"
```

**Comment by myhobby2** [comment]
Thanks for the help. I will post the results soon ;-)

**Comment by timetoexpire** [comment]
Could go in script at bottom and remove the # on

``` 
echo "paramter :${cf_setting_parameter_array[*]}"

echo "file :${cf_setting_file_array[*]}"
```

**Comment by timetoexpire** [comment]
You need to change as per your account at Cloudflare.

Here video of how it all done. You need to enter your own details which get from cloudflare/slack. Remove the -ipset my IP dosn't change that quickly ;) 

https://youtu.be/e1N5XLlAxc8
It not best video ever but would help understand. Hopefuly get idea. The strange error of invailed parameter option been defined. But hopeful the update will be out this mounth https://github.com/timetoexpire/cloudflare-ddns-updater/discussions/2

```
-auth_email=""
-slackuri="https://hooks.slack.com/services/XXX/YYY/ZZZ"
-zone_identifier="zi-tte"
-#="tte"
  -auth_method="token"
  -proxy="false"
  -proxy="true"
  -auth_key="ak-tte"
  -ipset="5.1.3.1"
  -record_name="test3.timetoexpire.co.uk"
  -sleep=10
  -ipcheck=
  -record_name="test3.timetoexpire.co.uk"
  -ipset="5.1.4.1"
  -record_name="test4.timetoexpire.co.uk"
  -sleep=20

-zone_identifier="zi-rp2"
-#="rp2"
  -proxy="true"
  -auth_key="ak-rp2"
  -ipset="5.1.1.1"
  -record_name="test1.rp2021.co.uk"
  -sleep=10
  -ipset="5.1.2.1"
  -record_name="test2.rp2021.co.uk"
  -sleep=20
  -rsleep=10

-zone_identifier="zi-tte"
-#="tte"
-auth_key="ak-tte"
  -ipset="5.1.3.2"
  -record_name="test3.timetoexpire.co.uk"
  -sleep=4
  -ipset="5.1.4.2"
  -record_name="test4.timetoexpire.co.uk"
  -sleep=20
  -rsleep=10

-zone_identifier="zi-rp2"
-#="rp2"
  -proxy="true"
  -auth_key="ak-rp2"
  -ipset="5.1.1.2"
  -record_name="test1.rp2021.co.uk"
  -sleep=10
  -ipset="5.1.2.2"
  -record_name="test2.rp2021.co.uk"
  -sleep=10

-zone_identifier="zi-rp2"
-#="rp2"
-auth_key="ak-rp2"
-ipcheck=""
-record_name="test1.rp2021.co.uk"
```

**Comment by myhobby2** [comment]
Thanks for your effort so far. Decided to create individual scripts per A record and call these via 1 batch in cron. It is very desirable to have this in 1 script but in case of a less easy setup, documentation is king. For people that are not aware of slackuri ( Like me ), this is a second dimension in this solution which is not pointed out.

Good (process) documentation and good examples are really an added-value to your effort. Love to use it, but I'm looking forward to a good manual

**Comment by timetoexpire** [comment]
First thanks for trying, and I have been able gain a little insight from your trials and tribulations.
The docments are already being updated. I not just the wording, but how it is formated/presented is also important.
You comments have been duly noted and hopeful you would choose to use my solution at a later date.

_Documentation is a weak spot of mine personally as I have dyslexia, but I always try to improve. [https://youtu.be/PEnJbjBuxnw](url) ;-)_
