### ISSUE TITLE
record won't update

### ISSUE THREAD

**Issue by gamb1t9** [K0p1-Git/cloudflare-ddns-updater#39]
Hello. I'm trying to get this thing to work. Modified the variables, and the script run manually prints out the expected message to syslog:

Apr 16 15:52:51 myhostname myusername: DDNS Updater: Check Initiated
Apr 16 15:52:52 myhostname myusername: DDNS Updater: 1.1.1.1 mycomain.com DDNS updated.

But it is not changing on the site. I'm new to Cloudflare and I have just registered this domain. Running the request manually, seems like it doing something:

{
  "result": [],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 100,
    "count": 0,
    "total_count": 0,
    "total_pages": 1
  }

But when I try to get DNS Record Details, I get:

{
  "result": [
    {
      "id": "blurred out",
      "zone_id": "blurred out",
      "zone_name": "mydomain.com", #ofc these are right
      "name": "mydomain.com",
      "type": "A",
      "content": "8.8.8.8", #old stuff I'd like to get rid of
      "proxiable": true,
      "proxied": false,
      "ttl": 1,
      "locked": false,
      "meta": {
        "auto_added": false,
        "managed_by_apps": false,
        "managed_by_argo_tunnel": false,
        "source": "primary"
      },
      "created_on": "2022-04-16T09:06:21.175273Z",
      "modified_on": "2022-04-16T13:37:12.440559Z"
    }
  ],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 100,
    "count": 1,
    "total_count": 1,
    "total_pages": 1
  }
}

I also tried getting a logs with the Get User Audit Logs API call, but indeed, these are completely missing from them. The last logged action is my manual setting of this A record. 

Why is telling me it's done its thing when it clearly has not?

I've tried to change the "proxy" variable to 'true' and turn it on on the site, then turned it off on the site and gave it "false" in the script, the exact same behavior. 

Am I doing something wrong? Is there some kind of delay, like "we tell you your API calls were successful but changes won't happen cuz you're too fresh"? Ofc I've verified my mail and all that. Manually chaning IPs do work. 

Idk if this is relevant, because pure API calls don't work, but hey, help out a brother

**Comment by Sailboat265** [comment]
Interesting, could you try to insert something like `logger -s "$update"` to see if the update request is actually being sent successfully?

**Comment by gamb1t9** [comment]
Okay It turns out (as usual) that it is an idiotic user error. 

Checking the response, $update was empty. Ofc I triple-checked my IDs/keys before posting, the one thing I forgot to check was my mail address, and I typed @mgail instead of gmail.

Although it is rather interesting for it to still be OK. Purposely giving the wrong mail to an API call (the logs retriever one), it is working as expected:

`
{
  "success": false,
  "errors": [
    {
      "code": 10000,
      "message": "Authentication error"
    }
  ]
}
`
So I guess $update shouldn't be empty.  

Anyway, thanks!

**Comment by simplytoast1** [comment]
I am having the same issue and I can confirm my information is correct.  HOWEVER my email does have a special character in it - both a dash and period.  Could that be the issue?

**Comment by Sailboat265** [comment]
@simplytoast1 Hi, did the script output anything?

**Comment by simplytoast1** [comment]
@Sailboat265  The script, no but in logger I get a successful update message.

DDNS Updater: XXX186.XXX.XXX x.xxxxxxxxxx.com DDNS updated.

(Redacted the proper information)

But in CF there is no update.  I tired both a scoped API and global API key.

For the environment I'm running MacOS

**Comment by simplytoast1** [comment]
I think something is a little larger at play because I purposely used a bad token and still got an DDNS updated note in my console.

**Comment by Sailboat265** [comment]
@simplytoast1 Sorry for the late reply. Good find of you, on finding that the script will still show update successful despite there are errors around.

Alright, since there are not enough information to check what exactly went wrong. I have modified the script a bit. You can get it [here](https://github.com/Sailboat265/cloudflare-ddns-updater/blob/main/dev-ipv4.sh).

Try using it to see if any useful debug information can be given to help your case.
