### ISSUE TITLE
Multi A records

### ISSUE THREAD

**Issue by snotifxtk** [K0p1-Git/cloudflare-ddns-updater#40]
Is there a way to change multiple dns A rcords with this script. 
if so how can i get this to work?

record_name="example1.com,example2.com"

**Comment by timetoexpire** [comment]
There few options.
1) have script set for each domain
2) make use of CNAME
3) use my script that be designed to do this https://github.com/timetoexpire/cloudflare-ddns-updater

**Comment by Shahin-rmz** [comment]
Hello, is this problem/feature still in progress and we have to use alternative methods mentioned above?
Thanks
