### ISSUE TITLE
Logger error

### ISSUE THREAD

**Issue by niklas2233** [K0p1-Git/cloudflare-ddns-updater#41]
hey i get an error on line 49 and 108 about logger command not found. im currently running it in windows with git bash but i want to use it in a truenas cron job
![NpzuCmA](https://user-images.githubusercontent.com/33903786/166998232-fa99b390-230b-492d-a3b6-09def1421a33.png)

**Comment by timetoexpire** [comment]
This is know issue. It down to Microsoft doing what Microsoft does. Logger is WSL doesn't work.
My version workaround for WLS.
https://github.com/timetoexpire/cloudflare-ddns-updater
