### ISSUE TITLE
Cloudflare IP not updating

### ISSUE THREAD

**Issue by Smartich0ke** [K0p1-Git/cloudflare-ddns-updater#42]
I have gotten this script to run without any errors but when I manually change one of my records on the Cloudflare dashboard, the script that is meant to change it does not. I have tried running it multiple times but to no avail. What should I do to find out more about why this is happening or how to fix it?

Here are the variables that I have set in the shell script file. Nothing else I have changed:
```
auth_email="REDACTED@gmail.com"             
auth_method="global"            
auth_key="REDACTED"           
zone_identifier="8b073b276e41fd6b61a6658678a83981"
record_name="node1"
ttl="3600"
proxy="true"
sitename="artichokemc.net"
slackchannel=""
slackuri=""
discorduri="https://discord.com/api/webhooks/REDACTED"
```

**Comment by Sailboat265** [comment]
So uhhhh... What exactly isn't working?
Did you mean that the script cannot update your record's IP after you manually changed something on the dashboard?

**Comment by Smartich0ke** [comment]
Yes. That 

> So uhhhh... What exactly isn't working? Did you mean that the script cannot update your record's IP after you manually changed something on the dashboard?

Yes that is what I mean. When I change a record manually, the script doesn't update it.

**Comment by Sailboat265** [comment]
I see, alright. I would suggest you to look into the audit log on Cloudflare to check if the request is getting passed or not.

In addition, please get this debug script from [here](https://github.com/Sailboat265/cloudflare-ddns-updater/blob/main/dev-ipv4.sh). Then, run it with `./dev-ipv4.sh --debug --force`

**Comment by shairyar** [comment]
I am running into the same issue, IP is not getting updated, I ran the scripting using `bash -x ./cloudflare.sh` and I can see it is an authentication error which is strange as I checked everything several times and everything is correct.

`{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}`

Maybe Cloudflare made some change that broke the script?

**Comment by shairyar** [comment]
It turned out to be an issue with `auth_method`, I was using a global key and did not set the value of it to be global. After setting that I can see the updated IP 👍🏼

**Comment by Smartich0ke** [comment]
I'm glad it worked for you. My auth method is on global and when I change it to something else it just throws an error.

**Comment by Smartich0ke** [comment]
I still have the problem. Does anybody know why this might be happening?

**Comment by Sailboat265** [comment]
@Smartich0ke I'm sorry, but it's really hard for anyone to help with the lack of debug information.

So, let me get this straight. When you say the script stopped working, do you mean it by **temporarily** or **endlessly**?
Uhhh, and you said you changed one of your records. What changes did you made?

And FYI, auth method only has two valid options. One is `token`, another one is `global`. When you use one that isn't matching to your Cloudflare API key type, of course it's going to throw an error.

**Comment by Smartich0ke** [comment]
When I manually change a record and run the script to see if it changes that record back to the public IP of the machine, it does not do so. The script appears to complete successfully with no errors and it doesn't matter how many times I run the script, the IP address for that record does not change.

**Comment by Sailboat265** [comment]
Thank you for the explanation. Hmmm, I tried to reproduce your issue, but everything worked fine.

Anyways, can you uhhh do a `bash -x ./your-script-name.sh` as mentioned by @shairyar. And what's the script actually doing?

**Comment by Smartich0ke** [comment]
Here is the output of  `bash -x ./script-name.sh`:

```
+ auth_email=REDACTED
+ auth_method=global
+ auth_key=REDACTED
+ zone_identifier=8b073b276e41fd6b61a6658678a83981
+ record_name=REDACTED
+ ttl=3600
+ proxy=true
+ sitename=REDACTED
+ slackchannel=
+ slackuri=
+ discorduri=REDACTED
+ ipv4_regex='([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])'
++ curl -s -4 https://cloudflare.com/cdn-cgi/trace
++ grep -E '^ip'
+ ip=ip=203.7.79.6
+ ret=0
+ [[ ! 0 == 0 ]]
++ echo ip=203.7.79.6
++ sed -E 's/^ip=(([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5]))$/\1/'
+ ip=203.7.79.6
+ [[ ! 203.7.79.6 =~ ^([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.([01]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])$ ]]
+ [[ global == \g\l\o\b\a\l ]]
+ auth_header=X-Auth-Key:
+ logger 'DDNS Updater: Check Initiated'
++ curl -s -X GET 'https://api.cloudflare.com/client/v4/zones/8b073b276e41fd6b61a6658678a83981/dns_records?type=A&name=REDACTED' -H 'X-Auth-Email: REDACTED' -H 'X-Auth-Key: REDACTED' -H 'Content-Type: application/json'
+ record='{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}'
+ [[ {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]} == *\"\c\o\u\n\t\"\:\0* ]]
++ echo '{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}'
++ sed -E 's/.*"content":"(([0-9]{1,3}\.){3}[0-9]{1,3})".*/\1/'
+ old_ip='{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}'
+ [[ 203.7.79.6 == {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]} ]]
++ echo '{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}'
++ sed -E 's/.*"id":"(\w+)".*/\1/'
+ record_identifier='{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}'
++ curl -s -X PATCH 'https://api.cloudflare.com/client/v4/zones/8b073b276e41fd6b61a6658678a83981/dns_records/{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}' -H 'X-Auth-Email: REDACTED' -H 'X-Auth-Key: REDACTED' -H 'Content-Type: application/json' --data '{"type":"A","name":"artichokemc.net","content":"REDACTED","ttl":"3600","proxied":true}'
+ update=
+ case "$update" in
+ logger 'DDNS Updater: REDACTED REDACTED DDNS updated.'
+ [[ '' != '' ]]
+ [[ REDACTED != '' ]]
+ curl -i -H 'Accept: application/json' -H Content-Type:application/json -X POST --data-raw '{
      "content" : "artichokemc.net Updated: REDACTED'\''s new IP Address is REDACTED"
    }' REDACTED
HTTP/2 204
date: Sat, 14 May 2022 02:29:41 GMT
content-type: text/html; charset=utf-8
set-cookie: __dcfduid=b5980eb4d32d11ecaf27c609b3e326c9; Expires=Thu, 13-May-2027 02:29:41 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-ratelimit-bucket: 3cd1f278bd0ecaf11e0d2391374c011d
x-ratelimit-limit: 5
x-ratelimit-remaining: 4
x-ratelimit-reset: 1652495384
x-ratelimit-reset-after: 2
x-envoy-upstream-service-time: 127
via: 1.1 google
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=rk9V9x%2FTyNlWI0yHbkXzWlecAp7A%2FsaU64q6l3E8NVYkZj6N7pDvJ5loePtXO4a85uw95pIQ7aDXdtLWKpKPqmSd%2B0Th6QxIDa9mAWkUaU9phTIxPpm32zSQvjOt"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
x-content-type-options: nosniff
set-cookie: __sdcfduid=b5980eb4d32d11ecaf27c609b3e326c98710cb9a882eb906a4e32d4c983cefedcdf01f5954f6bfa524489f8132f640a3; Expires=Thu, 13-May-2027 02:29:41 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/
set-cookie: __cfruid=1fd1a71996c3993317256ae9ff2c7fcc484178dd-1652495381; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 70b03524f9813772-MEL

+ exit 0
```

**Comment by Sailboat265** [comment]
Thanks so much for the log! That really helped the debug process!!!

Aha! I think I knew why now. After carefully looking through your log, it seems that the script failed to find the `record identifier`. The reason is shown as `'{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}'`

I would suggest you to double check all information in the variables are correct, mostly...
1. auth_email
2. auth_key
3. zone_identifier

Also, I have noticed another issue. Let's say your domain is named `artichokemc.net`. And you're trying to use this script to update a subdomain, let's say `node1.artichokemc.net`.

You need to setup the script like `record_name="node1.artichokemc.net"`, or else you will get an error.

**Comment by Smartich0ke** [comment]
Ah ok thanks for your help! I will check through those things and let you know if I get it working.

**Comment by Smartich0ke** [comment]
Yep, I re-entered the API token and fixed the record_name and now everything is working! Thanks @Sailboat265 for your help!

**Comment by Sailboat265** [comment]
@Smartich0ke Glad that you fixed it! Also, You're welcomed, anywhere, anytime!
