### ISSUE TITLE
Doesn't work after restart

### ISSUE THREAD

**Issue by R4ND0MC0D3** [K0p1-Git/cloudflare-ddns-updater#43]
Problem fixed

**Comment by Sailboat265** [comment]
Hi and uhhh... That shouldn't be happening. Can you do a `bash -x ./your-script-name.sh` and copy paste the log here? (You can redact sensitive information as needed) That should help in identifying where the problem is.

**Comment by R4ND0MC0D3** [comment]
how can we keep this one private, I'll be sharing private info ':D
