### ISSUE TITLE
TTL=auto

### ISSUE THREAD

**Issue by 00ihsan** [K0p1-Git/cloudflare-ddns-updater#46]
I can't set the TTL to auto.

**Comment by K0p1-Git** [comment]
Hi @00ihsan 

For TTL based on Cloudflare's API documentation. The input must be between 120 and 2,147,483,647 seconds, or 1 for automatic.

Regards

**Comment by 00ihsan** [comment]
oops... it works, thank you!

**Comment by K0p1-Git** [comment]
Welcome :))
