### ISSUE TITLE
TXT spf1 updater

### ISSUE THREAD

**Issue by duyuelryel** [K0p1-Git/cloudflare-ddns-updater#47]
Greetings! I try to use cloudflare to manage my email server's dns records too and i need an spf1 record but for that, i have to update the ip adress in the code too. Is there a way i can use your to do this please? What should i change in the code? Thank you!

The data should seems like this:

v=spf1 ip4:8.8.8.8 include:exampledomain.com~all

**Comment by Jeidnx** [comment]
Hey there!

first, a quick disclaimer: Having a mail server with a dynamic  IP address comes with a whole bunch of Issues and even risks. Other mail servers might not update their dns cache in time and the script probably won't update the dns records instantly after you get a new IP address. This can lead to mails not making it to your Inbox. I would highly suggest hosting your mail server on a server with a static public IP address. If that doesn't work in your case, you can look into Cloudflares email forwarding service.

Having the script update other record types as well, would require a pretty large change in the way the script works. For more complicated requests, i would suggest using python based scripts, as they are usually much easier to expand.
