### ISSUE TITLE
Cloudflare ip not updating

### ISSUE THREAD

**Issue by realunkn0wn** [K0p1-Git/cloudflare-ddns-updater#49]

**Comment by Sailboat265** [comment]
Hello there, first thing first, did you already redact sensitive info from the log dump you posted?

If haven't yet, please remove your comment immediately, and then regenerate your API key. You wouldn't want to take a security risk.

I repeat, delete your comment and then regenerate all Cloudflare API key immediately.

Then qfter you took care of the security issue, now, please ensure that you wrapped your credentials in quotes.

Just like this
```
auth_email = "helloworld123@gmail.com"
```
And take note that for the "proxy" variable, you can only set "true" or "false" not "yes"
Do like this
```
proxy = "true"
OR
proxy = "false"
BUT NOT
proxy = "yes"
```

**Comment by realunkn0wn** [comment]
alreadsy regenerated the api key after posted
