### ISSUE TITLE
[Discussion] remove the ttl and proxy variables

### ISSUE THREAD

**Issue by Jeidnx** [K0p1-Git/cloudflare-ddns-updater#58]
The ttl and proxy variables can be omitted from the cf api call which will result in them staying the same as they were. As these are not updated dynamically i would suggest omitting them from the script and leaving them to the cloudflare dashboard.

**Comment by Wizman87** [comment]
Including the TTL and proxy variables should be fine as Cloudflare defaults to a TTL of 300 seconds for "automatic" and Proxy Status of "true". However, it's possible that the records may get updated by a user or changed by a service that was not intended and the script enforces that with the included variables. This action may be desirable and advantageous to those using the script. Thoughts?

**Comment by Jeidnx** [comment]
As i see it we have two possible scenarios:

1. The script auto-updates ttl + proxy
Now if a user wanted to change it, he would have to do it via the script.
If you change something on the Cloudflare dashboard, expecting it to stay this way, you will be dissapointed.

2. The script doesn't update ttl + proxy
If a user wanted to change these values, he could do so via the cloudflare dashboard (or an api call).
There is no disappointment, because changing these values via the script is impossible.

In my opinion, scenario 2 is much preferable over scenario 1, as there is less that can go wrong.

Of course this is a minor issue, how often do you even update these things. But nonetheless it is something i noticed and I think it would be an improvement to the ux.

**Comment by Wizman87** [comment]
I won't lie, the first time I used the script, I didn't understand why my DNS record kept switching to DNS only from Proxied, so even for me I noticed some confusion. Though, another possible option might be to just keep the two variables blank by default, thereby still allowing the choice of the user. That would be a win-win scenario?

**Comment by K0p1-Git** [comment]
Thanks for bringing this up. I've not thought about the possibility of a lock-up by the script if it was predefined. I think what @Wizman87 mentioned is good, leaving it empty with documentation. 

Letting users make their own decisions when it comes to configuring the script to their needs.
