### ISSUE TITLE
where to find the url used for updating my dynamic ip 

### ISSUE THREAD

**Issue by AbdulMalek00** [K0p1-Git/cloudflare-ddns-updater#63]
I am trying to set ddns to work with raspberry pi 4 using dietpi 
they have built in ddns with custom ddns provider option and they ask for " the full URL used to update your dynamic IP against your custom DDNS provider "  where I can find that

**Comment by K0p1-Git** [comment]
https://www.whatismyip.com/

the following link should link you to your public-facing address. Cheers!
