### ISSUE TITLE
What am i doing wrong?? [Clouldflare's API does not support domains with a .cf, .ga, .gq, .ml, or .tk]

### ISSUE THREAD

**Issue by OusmBlueNinja** [K0p1-Git/cloudflare-ddns-updater#64]
![Captu1231231231re](https://user-images.githubusercontent.com/89956790/235029810-f9c2759d-e0cc-45e3-a340-1442c7d256d7.PNG)

it send the discord webhook and everything. but the dashboard ip doesent change

![image](https://user-images.githubusercontent.com/89956790/235029992-89c58340-09e2-403b-8ee9-7e1c848c9449.png)

**Comment by K0p1-Git** [comment]
Clouldflare's API does not support domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard.
