### ISSUE TITLE
I would like to add a Telegram Notification

### ISSUE THREAD

**Issue by peter-lxc** [K0p1-Git/cloudflare-ddns-updater#67]
Nice script thanks I have been playing around with adding a Telegram alert like slack and discord and it seems to work ok just needs an extra notification section like the others if you are interested i can share what i have working ?

**Comment by K0p1-Git** [comment]
Hi, I'll keep this issue up for those that share the same need as you, where they would be able to find access to the version of the script you've created. Thanks
