### ISSUE TITLE
Update loop without correct updates

### ISSUE THREAD

**Issue by LoginAsRoot** [K0p1-Git/cloudflare-ddns-updater#7]
Hey,
i have the problem, that the script works like it should according to the logs but the actual content of the A record isn't updated.
The script is in a update loop but dont update the content. I checked all auth inputs multiple times.

Do you think you can help me?

![Log](https://user-images.githubusercontent.com/65945369/128612201-28e5ba03-e08f-4441-b4d8-0df0f1168cec.PNG)

**Comment by K0p1-Git** [comment]
This is the first time I've encountered something like this. Maybe you can check to see if you are using the write auth method; either token or global. I'll leave the issue open, to see if anyone have similar issues.

**Comment by LoginAsRoot** [comment]
I found the error 😢 
my domain is a .tk domain. But for this case you the script should have recognized this error ("success": false,) because the last section ("Report the status") in the script is especially for this... weird that it didn't fail at this point 😞 

`{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1038,
      "message": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
    }
  ],
  "messages": []
}
`
