### ISSUE TITLE
Automatically updated ip address (subdomain) differes from the ip of the main domain

### ISSUE THREAD

**Issue by VakZok** [K0p1-Git/cloudflare-ddns-updater#70]
Hey guys,

I'm very new to this topic so please excuse stupid questions of mine.

I created a subdomain and gave it a random ip address to see if it will be changed by the script later. I then set up the script and checked, if the ip address of the subdomain was updated. It did. However, the automatically updated subdomain ip address differes from my main domain address. 

Is this normall or should they be equal? The reason I am asking is that whenever I try to visit my subdomain via browser, I get a connection error, while visiting my main domain works just fine.

If they should indeed match, I'd be very thankful for advice on how to fix this. Since the script works, I am quite sure to ave entered tokens, etc. correctly. But maybe there is another information or setting I have to enter/change.

Thank you in advance for your help!

**Comment by mrmarcus007** [comment]
Try making a entry with 
{
          "name": "@",
          "proxied": false
        }

it works for me.
