### ISSUE TITLE
Possibility to take IP from another gateway

### ISSUE THREAD

**Issue by denisjoshua** [K0p1-Git/cloudflare-ddns-updater#71]
Hi there, 
at my home I have 2 connections. (ADSL and 5G) 

I want to run the script in a server, but I want to take the IP from another router (gateway).
Is this possible please ? 

Thanks in advance 
Denis

**Comment by user8446** [comment]
Here are two ways to get the IP that way:

```
ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address'

ip route get 1.2.3.4 | awk '{print $7}'
```

**Comment by denisjoshua** [comment]
Thanks a lot :-)
