### ISSUE TITLE
DNS logged as updating but not actually updating.

### ISSUE THREAD

**Issue by n0t-r0n1t** [K0p1-Git/cloudflare-ddns-updater#79]
There is no error log of it not updating but it does not update.

![image](https://github.com/K0p1-Git/cloudflare-ddns-updater/assets/92458476/d65ff4f2-b28f-4c6d-bf68-4116ed10c369)

**Comment by ledude1** [comment]
nvm. I found out what the issue is.  I didn't change the auth_method from "token" to "global" since my key is a global key.  It works like a charm now.  Thanks so much for the script.
