### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by skarpinis** [K0p1-Git/cloudflare-ddns-updater#80]
cloudflare.sh: 22: [[: not found
cloudflare.sh: 31: [[: not found
cloudflare.sh: 39: [[: not found
cloudflare.sh: 58: [[: not found
cloudflare.sh: 68: [[: not found
cloudflare.sh: 109: [[: not found
cloudflare.sh: 116: [[: not found

**Comment by Sailboat265** [comment]
Hello @skarpinis, please refer to issue #9.

**Comment by skarpinis** [comment]
thanks
