### ISSUE TITLE
DDNS Updater failing due to "TTL must be a number not a string"

### ISSUE THREAD

**Issue by Konrad13x** [K0p1-Git/cloudflare-ddns-updater#86]
Hello. This error randomly started happening one day causing a major interruption in my services. I didn't change anything DNS nor in the script. Just randomly started outputting "TTL must be a number not a string."

![image](https://github.com/K0p1-Git/cloudflare-ddns-updater/assets/84676917/217dde4a-7897-4e53-9499-89bb165be8d8)

**Comment by K0p1-Git** [comment]
Hi, sorry for the disruption, Cloudflare decided to change their API. This issue should already be fixed in the lasted commit.
