### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by ikilzu** [K0p1-Git/cloudflare-ddns-updater#9]
Trying to run api and getting this errors and idk how to fix this

./cloudflare.sh: 17: [: xx.xx.xxx.xx: unexpected operator
./cloudflare.sh: 25: [: global: unexpected operator
./cloudflare.sh: 41: [[: not found
./cloudflare.sh: 51: [[: not found

**Comment by K0p1-Git** [comment]
Hi, can i know which version are you using? The experimental branch have not been fully tested. Instead do use the script in the main branch for a quick fix.

**Comment by SYLater** [comment]
I've got the same problem 
I'm using the main branch

**Comment by K0p1-Git** [comment]
are you able to provide the system logs? or does the script not run at all?

**Comment by SYLater** [comment]
> I've got the same problem
> I'm using the main branch

I fixed it by running "bash cloudflare.sh" instead of "./cloudflare.sh"

**Comment by K0p1-Git** [comment]
@SYLater oh, thanks for the info! 

@ikilzu  Right, after the previous merge the shebang is now set to sh and not bash for combability reasons. If you are using bash to run the script that explains the issue. Do use "bash cloudflare.sh" as mentioned by @SYLater to continue running the script in bash or use the sh interpreter.

**Comment by thinhplust** [comment]
./cloudflare.sh: 16: [: 27.69.180.0: unexpected operator
./cloudflare.sh: 24: [: unexpected operator
./cloudflare.sh: 40: [[: not found
./cloudflare.sh: 50: [[: not found
 how to fix

**Comment by K0p1-Git** [comment]
> @SYLater oh, thanks for the info! 
> 
> @ikilzu  Right, after the previous merge the shebang is now set to sh and not bash for combability reasons. If you are using bash to run the script that explains the issue. Do use "bash cloudflare.sh" as mentioned by @SYLater to continue running the script in bash or use the sh interpreter.   

@thinhplust my reply to ikilzu. Alternatively, you can change the shebang to bash and it will work. Or just $ bash ./cloudflare.sh

**Comment by thinhplust** [comment]
> > @ikilzu  Right, after the previous merge the shebang is now set to sh and not bash for combability reasons. If you are using bash to run the script that explains the issue. Do use "bash cloudflare.sh" as mentioned by @SYLater to continue running the script in bash or use the sh interpreter.

ok thanks pro
