### ISSUE TITLE
Error Message for TTL

### ISSUE THREAD

**Issue by Elijah-Dakota** [K0p1-Git/cloudflare-ddns-updater#92]
<13>Jun 25 10:15:34 root: {"result":null,"success":false,"errors":[{"code":9022,"message":"TTL must be a number, not a string."}],"messages":[]}

The TTL is set to the default of 3600. If this line is commented out it fails and says the the TTL must be filled out. If the quotations surround the number in the TTL is simply gives the same message.

**Comment by OlavAlexanderMjelde** [comment]
If you want Auto, set the value to 0.

**Comment by CodeDactyl** [comment]
Had this issue as well. It looks fixed in more recent updates of the script. To fix it on your end you can change the \"$ttl\" to $ttl in the update line.

**Comment by Elijah-Dakota** [comment]
Thank you I got the issue fixed, seemed to be a problem with cloudflare not liking the format.
