### ISSUE TITLE
TTL must be a number

### ISSUE THREAD

**Issue by egpgit** [K0p1-Git/cloudflare-ddns-updater#95]
Hi,
In the first place, I would like to give you tanks for your script.

I have been using it for months but now I get an error:
{"result":null,"success":false,"errors":[{"code":9022,"message":"TTL must be a number, not a string."}],"messages":[]}

I have updated de script with your last version that changes 2 lines (record_identifier line and --data line) but the error continues.
Could you told me what I am doing wrong?

I have realized that your last version changes the part of "--data" line in this way:
`:\"$ttl\",\"proxied\":${proxy}}")` for `:$ttl,\"proxied\":${proxy}}")` so ttl isn't a string its a number,  isn't?

I have the line:
`ttl="3600"                                          # Set the DNS TTL (seconds)`
I changed it for:
`ttl=3600                                          # Set the DNS TTL (seconds)`

same result

And I tried also change --data line deleting the var and putting the number with:
`--data "{\"type\":\"A\",\"name\":\"$record_name\",\"content\":\"$ip\",\"ttl\":3600,\"proxied\":${proxy}}")`

same result:  {"result":null,"success":false,"errors":[{"code":9022,"message":"TTL must be a number, not a string."}],"messages":[]}

Sorry for my poor english.

**Comment by egpgit** [comment]
Sorry It works now, I had done a backup of the file and I had executing the unchanged one....  Your code is perfect.

**Comment by flooxo** [comment]
Same here
`<13>Aug 13 15:06:45 root: DDNS Updater: <ip> <name> DDNS failed for <proxy (ip)>. DUMPING RESULTS:
<13>Aug 13 15:06:45 root: {"result":null,"success":false,"errors":[{"code":9022,"message":"TTL must be a number, not a string."}],"messages":[]}`

How to fix this?

**Comment by KammerlanderMario** [comment]
Hey @flooxo ,
you have to take the updated script. With git pull you can pull the new template and then use that template. I guess there is somewhere a declare in the script that changing the type in the head doesn't fix the problem.

**Comment by K0p1-Git** [comment]
see https://github.com/K0p1-Git/cloudflare-ddns-updater/pull/85
