### ISSUE TITLE
TTL dont change

### ISSUE THREAD

**Issue by DATAPOWERELECTRICAL** [K0p1-Git/cloudflare-ddns-updater#97]
I noticed when i change the seconds for false for proxy, it does not change on cloudflare... the minutes remain unchanged.

**Comment by DATAPOWERELECTRICAL** [comment]
hoping for release update with the fix.

**Comment by fyiyo** [comment]
It was fixed in that PR I shared. Check in your script that you are not using quotes.
It is clearer here:
https://github.com/K0p1-Git/cloudflare-ddns-updater/commit/7b1ba6eb2d058cae843a49b5cd87f40221ef7151

**Comment by DATAPOWERELECTRICAL** [comment]
sorry im kinder new to this.. do i need to reinstall this again or just make the changes without the quotes for ttl and  --data ttl part too ?

**Comment by fyiyo** [comment]
You only need to remove the quotes as you see in that PR. There are 2 locations.

**Comment by DATAPOWERELECTRICAL** [comment]
will a sudo git clone resolve this or always need to do this to change.. ?
